title: EmojisRMe
author: Anne of Green Gables
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Here I will present and discuss my effervescent love of emoji :smiley:

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
